config:
  router:
  - id: Router.E2
    mode: edge

  listener:
  - host: 0.0.0.0
    port: 5672
    saslMechanisms: ANONYMOUS

  connector:
  # Edge connector to Interior I2
  - role: edge-uplink
    host: Router.I2.lab0
    port: 5674
    saslMechanisms: ANONYMOUS

  log:
  - module: ROUTER
    enable: trace+