config:
  router:
  - id: Router.I1
    mode: interior

  listener:
  # Standard AMQP listener
  - host: 0.0.0.0
    port: 5672
    saslMechanisms: ANONYMOUS

  # Internal router communication
  - role: inter-router
    host: 0.0.0.0
    port: 5673
    saslMechanisms: ANONYMOUS

  # Edge router listener
  - role: edge-uplink
    host: 0.0.0.0
    port: 5674
    saslMechanisms: ANONYMOUS

  connector:
  # Broker A
  - host: Broker.A.lab0
    port: 5672
    saslMechanisms: ANONYMOUS

  log:
  - module: ROUTER
    enable: trace+