---
- hosts: docker-host
  tasks:
    - include_tasks: tasks/deploy_docker.yml
    - include_tasks: tasks/deploy_brokers.yml
    - include_tasks: tasks/deploy_routers.yml
    - include_tasks: tasks/deploy_clients.yml
